name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.4"
        bundler-cache: true
        working-directory: android
    
    - name: Clean Flutter and Gradle caches
      run: |
        flutter clean
        cd android
        ./gradlew clean
    
    - name: Install Dependencies
      run: |
        flutter pub get
        bundle install
      working-directory: android
    
    - name: Build APK
      run: flutter build apk --release --verbose
      working-directory: android
    
    - name: Build and Distribute App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
        cd android
        bundle exec fastlane android firebase_distribution --verbose
